# https://taskfile.dev

version: '3'

vars:
  PROJECT: coreimage

tasks:
  default:
    dir: src/
    cmds:
      - mamba run -n {{.PROJECT}} python -m {{.PROJECT}} {{.CLI_ARGS}}
    silent: true

  export:
    desc: export env
    cmds:
      - conda env export --no-builds  -n {{.PROJECT}} > environment.yml

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true

  build:
    desc: build
    cmds:
      - rm -rf dist/*
      - mamba run -n {{.PROJECT}} python  -m build

  install:
    desc: install
    cmds:
      - task: build
      - find dist -type f -name "*.whl" | head -n 1 | xargs pip install


  publish:
    desc: publish
    cmds:
      - scp dist/* muzak:/var/www/pypi/packages/{{.PROJECT}}

  deploy:
    desc: all
    cmds:
      - task: push
      - task: build
      - task: publish